modLoader="javafml"
loaderVersion="[46,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Player%20Tracking"
logoFile="icon.png"

[[mods]]
modId="playertracking"
version="3.0"
displayName="Player Tracking"
displayURL="https://curseforge.com/minecraft/mc-mods/player-tracking"
authors="Rick South"
description='''A PvP mod which allows tracking players via trackers in the world, originally created by mcpvp.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.playertracking]]
    modId="collective"
    mandatory=true
    versionRange="[6.56,)"
    ordering="NONE"
    side="BOTH"